# Generated by Django 3.0.3 on 2020-08-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0009_auto_20200810_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
