# Generated by Django 3.0.3 on 2020-08-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0010_auto_20200810_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='prefecture',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
