# Generated by Django 3.0.3 on 2020-06-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_auto_20200616_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='good',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
