# Generated by Django 3.0.3 on 2020-06-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0004_auto_20200617_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
