# Generated by Django 3.0.3 on 2020-07-04 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0005_auto_20200703_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='good',
            new_name='like',
        ),
    ]
