# Generated by Django 3.0.3 on 2020-06-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0005_auto_20200617_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.AddField(
            model_name='post',
            name='good',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
