# Generated by Django 3.0.3 on 2020-06-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0007_auto_20200618_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='good',
            field=models.IntegerField(default=0),
        ),
    ]
