# Generated by Django 3.0.3 on 2020-06-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0010_auto_20200618_2025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
