# Generated by Django 3.0.3 on 2020-06-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0013_likebuttonmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='good',
        ),
    ]
