# Generated by Django 3.0.3 on 2020-06-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0014_remove_post_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='good',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='LikeButtonModel',
        ),
    ]
