# Generated by Django 3.0.3 on 2020-06-22 14:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon_image',
            field=models.FileField(blank=True, default='images/custom_user/icon_image/icon.png', null=True, upload_to=accounts.models.get_icon_image_path, verbose_name='アイコン画像'),
        ),
    ]
