# Generated by Django 3.0.3 on 2020-08-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0008_auto_20200810_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='prefecture',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
